"""add_email_and_purpose_to_otp_verifications

Revision ID: 3652d98b88df
Revises: a7967992c051
Create Date: 2025-09-14 21:17:52.259613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3652d98b88df'
down_revision: Union[str, None] = 'a7967992c051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('otp_verifications', sa.Column('purpose', sa.String(length=50), nullable=False))
    op.add_column('otp_verifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('otp_verifications', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_otp_verifications_email'), 'otp_verifications', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_verifications_email'), table_name='otp_verifications')
    op.alter_column('otp_verifications', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('otp_verifications', 'created_at')
    op.drop_column('otp_verifications', 'purpose')
    op.drop_column('otp_verifications', 'email')
    # ### end Alembic commands ###
