"""Add task models - ServiceRequest, TaskAssignment, TaskNotification

Revision ID: a7967992c051
Revises: ccc8885970f0
Create Date: 2025-09-03 23:23:02.327585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7967992c051'
down_revision: Union[str, None] = 'ccc8885970f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=False),
    sa.Column('client_phone', sa.String(length=20), nullable=True),
    sa.Column('service_title', sa.String(length=200), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=False),
    sa.Column('service_category', sa.String(length=100), nullable=False),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('expected_duration', sa.String(length=100), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_preference', sa.String(length=255), nullable=True),
    sa.Column('remote_work_allowed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'REJECTED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('preferred_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_request_id', sa.UUID(), nullable=False),
    sa.Column('proz_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('assignment_notes', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('proposed_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'REJECTED', name='taskstatus'), nullable=False),
    sa.Column('proz_response', sa.Text(), nullable=True),
    sa.Column('proz_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proz_id'], ['proz_profiles.id'], ),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proz_id', sa.UUID(), nullable=False),
    sa.Column('task_assignment_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_email_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proz_id'], ['proz_profiles.id'], ),
    sa.ForeignKeyConstraint(['task_assignment_id'], ['task_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_notifications')
    op.drop_table('task_assignments')
    op.drop_table('service_requests')
    # ### end Alembic commands ###
