"""Update Proz Profile with additional fields

Revision ID: f196d24d45a0
Revises: ef58c0de149c
Create Date: 2025-05-06 14:13:58.715032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f196d24d45a0'
down_revision: Union[str, None] = 'ef58c0de149c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prozprofile', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('prozprofile', sa.Column('verification_token', sa.String(length=100), nullable=True))
    op.add_column('prozprofile', sa.Column('education', sa.Text(), nullable=True))
    op.add_column('prozprofile', sa.Column('certifications', sa.Text(), nullable=True))
    op.add_column('prozprofile', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('prozprofile', sa.Column('linkedin', sa.String(length=255), nullable=True))
    op.add_column('prozprofile', sa.Column('preferred_contact_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prozprofile', 'preferred_contact_method')
    op.drop_column('prozprofile', 'linkedin')
    op.drop_column('prozprofile', 'website')
    op.drop_column('prozprofile', 'certifications')
    op.drop_column('prozprofile', 'education')
    op.drop_column('prozprofile', 'verification_token')
    op.drop_column('prozprofile', 'email_verified')
    # ### end Alembic commands ###
